### ISSUE TITLE
Reminder about updating files to all branches

### ISSUE THREAD

**Issue by JAMESY9868** [TrinityTrihawks/2017#5]
## The following file modifications should be applied to all branches:

Update .gitignore
Delete .classpath (Note that if a local .classpath file is deleted, one needs to remove the 2017 project from eclipse, **create** a new java project, and run `./gradlew eclipse` in the 2017 directory)
Delete .metadata directory
Update build.gradle

**Comment by JAMESY9868** [comment]
@WawerOS

**Comment by WawerOS** [comment]
All done!
